export const outfits = [
    { id: 'aceh', name: 'Ulee Balang (Aceh)' },
    { id: 'sumut', name: 'Ulos (Sumatera Utara)' },
    { id: 'sumbar', name: 'Bundo Kanduang / Penghulu (Sumatera Barat)' },
    { id: 'riau', name: 'Melayu Jatuh (Riau)' },
    { id: 'kepulauan_riau', name: 'Teluk Belanga (Kepulauan Riau)' },
    { id: 'jambi', name: 'Baju Kurung Tanggung (Jambi)' },
    { id: 'sumsel', name: 'Aesan Gede (Sumatera Selatan)' },
    { id: 'babel', name: 'Pakaian Seting / Cual (Bangka Belitung)' },
    { id: 'bengkulu', name: 'Rejang Lenong (Bengkulu)' },
    { id: 'lampung', name: 'Tulang Bawang Siger (Lampung)' },
    { id: 'jakarta', name: 'Kebaya Encim / Sadariah (DKI Jakarta)' },
    { id: 'jabar', name: 'Kebaya Sunda (Jawa Barat)' },
    { id: 'banten', name: 'Baju Pangsi (Banten)' },
    { id: 'jateng', name: 'Jawi Jangkep / Kebaya (Jawa Tengah)' },
    { id: 'diy', name: 'Kesatrian Ageng (DI Yogyakarta)' },
    { id: 'jatim', name: 'Pesa\'an Madura (Jawa Timur)' },
    { id: 'bali', name: 'Payas Agung (Bali)' },
    { id: 'ntb', name: 'Rimpu / Pegon (NTB)' },
    { id: 'ntt', name: 'Amarasi (NTT)' },
    { id: 'kalbar', name: 'King Baba & King Bibige (Kalimantan Barat)' },
    { id: 'kalteng', name: 'Upak Nyamu (Kalimantan Tengah)' },
    { id: 'kalsel', name: 'Bagajah Gamuling (Kalimantan Selatan)' },
    { id: 'kaltim', name: 'Takwo (Kalimantan Timur)' },
    { id: 'kalut', name: 'Ta\'a dan Sapei Sapaq (Kalimantan Utara)' },
    { id: 'sulut', name: 'Laku Tepu (Sulawesi Utara)' },
    { id: 'sulteng', name: 'Nggembe (Sulawesi Tengah)' },
    { id: 'sulsel', name: 'Baju Bodo (Sulawesi Selatan)' },
    { id: 'sultra', name: 'Babu Nggawi (Sulawesi Tenggara)' },
    { id: 'gorontalo', name: 'Bili\'u (Gorontalo)' },
    { id: 'sulbar', name: 'Lipa Saqbe Mandar (Sulawesi Barat)' },
    { id: 'maluku', name: 'Baju Cele (Maluku)' },
    { id: 'malut', name: 'Manteren Lamo (Maluku Utara)' },
    { id: 'papua', name: 'Rok Rumbai & Noken (Papua)' },
    { id: 'papua_barat', name: 'Ewer (Papua Barat)' },
    { id: 'papua_selatan', name: 'Asmat High Fashion (Papua Selatan)' },
    { id: 'papua_tengah', name: 'Mee High Fashion (Papua Tengah)' },
    { id: 'papua_pegunungan', name: 'Dani High Fashion (Papua Pegunungan)' },
    { id: 'papua_barat_daya', name: 'Kain Timur High Fashion (Papua Barat Daya)' }
];
